name: Binary

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        targetos: [windows, darwin, linux]
    name: ${{ matrix.arch }}-${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt install apt-transport-https curl gnupg
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
          sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
          sudo echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" > /etc/apt/sources.list.d/bazel.list
      - run: |
          bazel build @com_google_protobuf//:protoc
          bazel build //firebase_rules_generator:protoc-gen-firebase_rules --platforms=//:${{ matrix.targetos }}-${{ matrix.arch }}

      - uses: actions/upload-artifact@v2
        with:
          name: protoc-gen-firebase_rules-${{ matrix.targetos }}-${{ matrix.arch }}
          path: bazel-bin/firebase_rules_generator/protoc-gen-firebase_rules
